image: "scorpil/rust:nightly"

before_script:
- apt-get update -yqq
- apt-get install -yqq --no-install-recommends build-essential libssl-dev pkg-config

test:cargo:
  script:
  - rustc --version && cargo --version
  - cargo test --verbose --jobs 1 --release
